[package]
name = "fightlines-server"
version = "0.1.0"
authors = ["Chad Stearns <chadtech0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
fightlines_moves = { path = "../moves" }