[package]
name = "code-gen"
version = "0.1.0"
authors = ["Chadtech <chadtech0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "0.3"
protobuf-codegen-pure = "2.3"