[package]
name = "fightlines-ui"
version = "0.1.0"
authors = ["Chadtech <chadtech0@gmail.com>"]
edition = "2018"

[dependencies]
# for web_sys
yew = { version = "0.15", package = "yew-stdweb" }
wasm-bindgen = "0.2"
