name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: rust-rustfmt-check
      uses: mbrobbel/rustfmt-check@0.2.0
      # with:
        # GitHub token
        # token: 
        # Arguments for cargo. Not for rustfmt options.
        # args: # optional
